services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Respons11
      MYSQL_DATABASE: booking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./bdd:/docker-entrypoint-initdb.d

volumes:
  my-db:
